services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: device_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql80
    networks:
      - devnet
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 60s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - devnet

volumes:
    mysql_data:

networks:
    devnet: